version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
       - "3100:3000"
  client:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/app
    depends_on:
      - api
    ports:
       - "3000:3000"
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - /tmp/postgresql:/var/run/postgresql
